title: <p align="center"> Sora Ryu </p> # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
  <p align="justify">
  I am currently a Machine Learning Intern at National Renewable Energy Laboratory with a focus on Computer Vision and Deep Learning research.
  <br><br>
  </p>

  <p align="center">
  <a href="https://www.linkedin.com/in/sora-ryu-89b2661b0/">LinkedIn</a> |
  <a href="pdf/SoraRyu_081323.pdf">Resume</a> |
  <a href="https://github.com/sora-ryu">GitHub</a>
  </p>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
