title: <p align="center"> Sora Ryu </p> # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
  <p align="justify">
  I am currently a Machine Learning Intern at NREL with a focus on Computer Vision and Deep Learning research.
  <br><br>
  My research lies in the intersection of machine learning and computer vision. The goal of my research is to contribute to the world where humans and AI could peacefully coexist
  </p>

  <p align="center">
  <a href="https://www.linkedin.com/in/sora-ryu-89b2661b0/">LinkedIn</a> |
  <a href="pdf/SoraRyu_081323.pdf">Resume</a> |
  <a href="https://github.com/sora-ryu">GitHub</a>
  </p>

theme: jekyll-theme-minimal
